version: '3.8'

services:
  db:
    image: ankane/pgvector:latest
    container_name: facerecog_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: facerecog
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  face-analyzer-trt:
    build:
      context: .
      dockerfile: Dockerfile.trt
    container_name: face_analyzer_trt
    ports:
      - "8081:8000"
    volumes:
      - .:/app
      - ./trt_cache:/app/trt_cache
      - ./insightface_models:/root/.insightface/models
      - ./pip_cache:/root/.cache/pip
    environment:
      # Указываем адрес твоего C# сервиса в Visual Studio
      - CSHARP_BACKEND_URL=https://host.docker.internal:7094/api/attendance/process-faces
    # КРИТИЧЕСКИ ВАЖНО: Позволяет контейнеру видеть твой Windows/VS
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Теперь он зависит от db только формально, если бэкенд C# требует готовности базы
    depends_on:
      - db

volumes:
  postgres_data: